### PR TITLE
Add SwiftPM support

### PR DESCRIPTION
**Pull request by AYastrebov**
just add a new tag to create a new release and this should work

### CODE REVIEW

**Comment by AdeptusAstartes** [comment]
Please restore the deleted files.  They are not unused.

**Review by AdeptusAstartes — CHANGES_REQUESTED** [review]
Please restore all deleted files.  They are not unused.

**Comment by AYastrebov** [comment]
reverted the commit. But I still sure this files are not needed

**Comment by AYastrebov** [comment]
@AdeptusAstartes what do you think?

**Pull request closed without merging**
